export const TENDER_STATUS_CONFIG = {
  NEW: {
    label: 'Новый',
    variant: 'info',
    icon: 'Sparkles',
    color: '#e0f2fe',
    textColor: '#0369a1',
  },
  DOCUMENTS_LOADING: {
    label: 'Загрузка документов',
    variant: 'warning',
    icon: 'FileDown',
    color: '#fef3c7',
    textColor: '#b45309',
  },
  DOCUMENTS_LOADED: {
    label: 'Документы загружены',
    variant: 'warning',
    icon: 'FileCheck',
    color: '#fef3c7',
    textColor: '#b45309',
  },
  PROCESSING: {
    label: 'Обработка',
    variant: 'info',
    icon: 'Cog',
    color: '#ddd6fe',
    textColor: '#6d28d9',
  },
  SEMANTIC_FILTERING: {
    label: 'Семантический анализ',
    variant: 'info',
    icon: 'Brain',
    color: '#ddd6fe',
    textColor: '#6d28d9',
  },
  RELEVANT: {
    label: 'Релевантный',
    variant: 'success',
    icon: 'CheckCircle',
    color: '#d1fae5',
    textColor: '#047857',
  },
  UNCERTAIN: {
    label: 'Неуверенный',
    variant: 'warning',
    icon: 'HelpCircle',
    color: '#fef3c7',
    textColor: '#b45309',
  },
  NOT_RELEVANT: {
    label: 'Не релевантный',
    variant: 'secondary',
    icon: 'XCircle',
    color: '#e5e5e5',
    textColor: '#525252',
  },
  SCORING: {
    label: 'Скоринг',
    variant: 'info',
    icon: 'Calculator',
    color: '#ddd6fe',
    textColor: '#6d28d9',
  },
  SCORED: {
    label: 'Оценен',
    variant: 'success',
    icon: 'Gauge',
    color: '#d1fae5',
    textColor: '#047857',
  },
  AWAITING_SUPPLIER_SEARCH: {
    label: 'Ожидает поиска',
    variant: 'warning',
    icon: 'Search',
    color: '#fef3c7',
    textColor: '#b45309',
  },
  SUPPLIER_SEARCH_IN_PROGRESS: {
    label: 'Поиск поставщиков',
    variant: 'info',
    icon: 'Radar',
    color: '#ddd6fe',
    textColor: '#6d28d9',
  },
  SUPPLIERS_FOUND: {
    label: 'Поставщики найдены',
    variant: 'success',
    icon: 'Users',
    color: '#d1fae5',
    textColor: '#047857',
  },
  NO_SUPPLIERS_FOUND: {
    label: 'Поставщики не найдены',
    variant: 'danger',
    icon: 'UserX',
    color: '#fee2e2',
    textColor: '#b91c1c',
  },
  AWAITING_CP: {
    label: 'Ожидает КП',
    variant: 'warning',
    icon: 'FileClock',
    color: '#fef3c7',
    textColor: '#b45309',
  },
  CP_REQUESTED: {
    label: 'КП запрошено',
    variant: 'info',
    icon: 'Send',
    color: '#ddd6fe',
    textColor: '#6d28d9',
  },
  CP_PARTIALLY_RECEIVED: {
    label: 'КП частично получены',
    variant: 'warning',
    icon: 'FilePartial',
    color: '#fef3c7',
    textColor: '#b45309',
  },
  CP_FULLY_RECEIVED: {
    label: 'КП полностью получены',
    variant: 'success',
    icon: 'FileFull',
    color: '#d1fae5',
    textColor: '#047857',
  },
  NEGOTIATING: {
    label: 'Переговоры',
    variant: 'info',
    icon: 'Handshake',
    color: '#ddd6fe',
    textColor: '#6d28d9',
  },
  READY_FOR_DECISION: {
    label: 'Готов к решению',
    variant: 'success',
    icon: 'ClipboardCheck',
    color: '#d1fae5',
    textColor: '#047857',
  },
  APPROVED: {
    label: 'Одобрен',
    variant: 'success',
    icon: 'ThumbsUp',
    color: '#10b981',
    textColor: '#ffffff',
  },
  REJECTED: {
    label: 'Отклонен',
    variant: 'danger',
    icon: 'ThumbsDown',
    color: '#ef4444',
    textColor: '#ffffff',
  },
  ERROR: {
    label: 'Ошибка',
    variant: 'danger',
    icon: 'AlertTriangle',
    color: '#fee2e2',
    textColor: '#b91c1c',
  },
} as const;

export const TENDER_STATUSES = Object.keys(TENDER_STATUS_CONFIG);